### ISSUE TITLE
Create web authentication mechanism

### ISSUE THREAD

**Issue by EtienneDx** [EtienneDx/git-mentor#10]
**As a** User, **I want to** authenticate myself, **So that** I can access securely my personal data.

To authenticate, jwt should be used. The jwt should contain the basic information about the user, such as its id, name and email.

An authorization middleware should also be created to be used by other APIs later on, returning the user data contained in the jwt. The goal of the jwt is to reduce the number of database queries using the informations within.

On the front-end side, an email-password page should be created, saving the jwt in an app state. Decision regarding the use of redux should be made independently of this story, as part of the previous infrastructure task.

**Comment by Marin-de-Drouas** [comment]
For App security we can use _"Javascript Object Signing and Encryption"_ in order to authenticate users, it requires RSA Key generation and storage but it is pretty easy to implement.

**Comment by EtienneDx** [comment]
Looking at the wiki, one of their RFC is JWT, which is the one I recommended here :)

**Comment by Marin-de-Drouas** [comment]
Yes absolutely that's why i thought about it

**Comment by EtienneDx** [comment]
I meant jwt are one of the Jose standard :)

**Comment by EtienneDx** [comment]
First part done, still needs to figure out the middleware part of the authentication. See #33
