### ISSUE TITLE
Setup front-end project

### ISSUE THREAD

**Issue by EtienneDx** [EtienneDx/git-mentor#4]
Create a new react app to access the API. Setup should be a simple app, without any specific behavior. It should setup a clean project, with main libraries already added, to encourage a straightforward tree for later commits.

**Comment by Marin-de-Drouas** [comment]
What should be those main libraries?

**Comment by EtienneDx** [comment]
I’m not 100% sure, I’m guessing having a style library could be useful, we’ll probably need something like fa icons too. Apart from that, I think we’ll need some kind of routing so react router makes sense I think, as the app won’t be a one pager.
So yeah I’m guessing these 3 would be nice. Maybe consult with Frallo, he might have some nice insight?

**Comment by EtienneDx** [comment]
If you can add some ci too to enforce style and maybe some unit tests that’s be cool too

**Comment by Marin-de-Drouas** [comment]
I used react-router-dom, react-fontawesome and styled-components as basic libs.
I also added CI but not sure if i did it right as Rust CI is at root and React CI in the App file  ¯\_(ツ)_/¯

**Comment by Marin-de-Drouas** [comment]
Unit tests are in App.test.js

**Comment by EtienneDx** [comment]
CI should probably be at root too for github to see it. Share the CR I'll let you know :)

**Comment by Marin-de-Drouas** [comment]
I dedicated 3 hours to clean some dependancies vulnerabilities, finally got only 3 moderate severity vulnerabilities but can't get rid of it ... 

You can check the CI that may not be at the right place at least we are on typescript now!

**Comment by EtienneDx** [comment]
Nice, I don't have the code yet but I'll take a look. Vulnerabilities are relatively common with node, I'll take a look to see if I can clean them but we might be somewhat stuck with it

**Comment by EtienneDx** [comment]
Another question here: should we use redux? Might be somewhat overkill although it might be useful to have a better management over what we're looking at and keep some stuff in cache easily?

**Comment by Marin-de-Drouas** [comment]
Found an interesting topic about that: https://stackoverflow.com/questions/49574285/how-to-cache-fetched-data-in-react-without-redux
We have 3 options if we want to avoid redux:
- Local storage (That seems to be an unpopular option)
- Storing the state in a parent component that isn't unmounting and giving access to the data and the state setter to your relevant component through props.
- Setting up a context provider for the state, storing it there, and then subscribing to that context where you need it with the useState hook or a context consumer.

**Comment by EtienneDx** [comment]
My take on it:
- local storage is a pain, redux is a wrapper around it
- state is a pain, it would turn into a prop being passed all over the place
- context is a must, altough it wouldn't store stuff locally. Not sure that's a bad thing but it's to be taken into consideration

**Comment by Lerri-Cofannos** [comment]
Decision was made to switch from `styles-components` to `tailwindcss`. `prettier` and `eslint` got added for formatting and linting. A draft auth was set up to showcase the file structure.
