### ISSUE TITLE
Add proper CI to facilitate checking PR

### ISSUE THREAD

**Issue by EtienneDx** [EtienneDx/git-mentor#41]
In order to facilitate the checking of new features, a CI can be put into place.

For our purpose, the new CI should, **on push**:
- Build the artefacts
- Upload the frontend to a bucket
  - One per CR would work, as the bucket would be deleted after the CR is merged/closed
- Creates a disabled CloudFront distribution to grant access to said bucket (single region)
- Upload the backend artefacts to a separate bucket
  - One for all CRs would be better here, to simplify access
- Create a cloudwatch log group
- Create IAM user to access said group + Upload 
This Action should be reusable

A separate manual action should start the server **when manually triggered**:
- Validate the frontend stack existence / status
- Enable the cloudfront distribution
- Create VPC etc
- Start an ec2 instance with a custom build script which:
  - Downloads the backend artefacts from the artefact bucket
  - Start a database
  - Start the different services
  - Send logs to the log group
  - Run custom startup script to seed the environment (sql/ts script?) @Lerri-Cofannos any input on this?
- Upload `config.json` to frontend S3 bucket, giving the frontend the URL to the back
- Create an alarm if the server stays up for more than a given time
  - Potentially destroying the stack?

Another manual action should stop the server **when manually triggered**:
- Remove the backend stack entirely

A final stack should be used **on merge, on close**:
- Remove the backend stack if it is running
- Remove the frontend stack
- Any failure should trigger an alarm

**Comment by Lerri-Cofannos** [comment]
The backend should be the one to seed the database, using the regular functions used for creating entities. I suggest adding a script that gets triggered at launch if a certain environnement variable is set. The variable could be injected in commands through a flag, or directly set in the CI.

**Comment by EtienneDx** [comment]
Here's a simplified graph of the goal for this CR.This will need to be further refined during the implementation

![ci](https://github.com/EtienneDx/git-mentor/assets/32039535/34764cc1-d252-4a54-bd54-043f00c0976f)

**Comment by EtienneDx** [comment]
Closed with #45
